name: app_todo_lovepeople
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
 

  uses-material-design: true

  assets: 
   - assets/images/logolovepeople.png
   - assets/fonts/Montserrat-Bold.ttf
   - assets/fonts/Montserrat-SemiBold.ttf
   - assets/fonts/Tahoma.ttf
  
 